### ISSUE TITLE
hammer-api returns 502 Internal Server Error

### ISSUE THREAD

**Issue by mwkaufman** [dowjones/hammer#88]
hammer-api returns 502 Internal Server Error on call to LATEST/identify.

From hammer-api CloudWatch logs:
```'topic_name': KeyError
Traceback (most recent call last):
File "/var/task/entrypoint.py", line 22, in wrapper
response = handler(event, context)
File "/var/task/entrypoint.py", line 191, in lambda_handler
return start_scan(account_id, regions, security_features, tags, ids)
File "/var/task/entrypoint.py", line 95, in start_scan
topic_name = config.get_module_config_by_name(security_feature).sns_topic_name
File "/var/task/library/config.py", line 532, in sns_topic_name
return self._config['topic_name']
KeyError: 'topic_name'
```

**Comment by pranav1688** [comment]
Thanks @mwkaufman  for the solution you provided. We have merged the fix
